name: Cache Node and NPM Dependencies
description: "This action allows to cache both Node and NPM dependencies based on the package-lock.json file."
inputs:
  node-version:
    description: NodeJS version to use
    default: '20.x'
    required: true
  working-dir:
    description: The working directory of the application
    default: '.'
runs:
  using: composite
  env:
    CACHE_PATH: ${{ inputs.working-dir }}/node_modules
    LOCKFILE_PATH: ${{ inputs.working-dir }}/package-lock.json
  steps:
    - name: Setup NodeJS version ${{ inputs.node-version}}
      uses: actions/setup-node@v6
      with:
        node-version: ${{ inputs.node-version }}
    - name: Cache dependencies
      id: cache
      uses: actions/cache@v4
      with:
        path: ${{ env.CACHE_PATH }}
        key: ${{ runner.os }}-node-${{ hashFiles(env.LOCKFILE_PATH) }}
    - name: Install Dependencies
      if: ${{ steps.cache.outputs.cache-hit != 'true' }}
      working-directory: ${{ inputs.working-dir }}
      shell: bash
      run: npm ci
