name: Cache Node and NPM Dependencies
description: "This action allows to cache both Node and NPM dependencies based on the package-lock.json file."
inputs:
  node-version:
    description: NodeJS version to use
    default: '20.x'
    required: true
  working-dir:
    description: The working directory of the application
    default: .
    required: false
  target-env:
    description: "'dev' or 'prod'. Controls whether dev dependencies are installed."
    required: false
    type: choice
    options:
      - dev
      - prod
    default: dev
runs:
  using: composite
  steps:
    - name: Setup NodeJS version ${{ inputs.node-version}}
      uses: actions/setup-node@v6
      with:
        node-version: ${{ inputs.node-version }}
    - name: Cache dependencies
      id: cache
      uses: actions/cache@v4
      with:
        path: ${{ inputs.working-dir }}/node_modules
        key: ${{ runner.os }}-node-${{ hashFiles(format('{0}/{1}', inputs.working-dir, 'package-lock.json')) }}
    - name: Install Dependencies
      if: ${{ steps.cache.outputs.cache-hit != 'true' }}
      working-directory: ${{ inputs.working-dir }}
      shell: bash
      run: ${{ inputs.target-env == 'dev' && 'npm ci' || 'npm ci --omit-dev' }}
