name: 17 - 2 - Custom Actions - JS
on:
  workflow_dispatch:
run-name: 17 - 2 - Custom Actions - JS
jobs:
  dependency-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Check for dependency updates
        uses: ./.github/actions/js-dependency-update
