name: Update NPM Dependencies
description: "Checks if there are updates to NPM packages, and creates a PR with the updated package*.json files"
inputs:
  base-branch:
    description: "The branch used as the base for the dependency update checks."
    type: string
    required: false
    default: main
  head-branch:
    description: "The branch from which the PR is created."
    type: string
    required: false
    default: update-dependencies
  working-directory:
    description: "The working directory of the project to check for dependency updates."
    required: true
    default: "./sample-apps/react-app"
  gh-token:
    description: "Authentication token with repository access. Must have write access to contents and pull-requests."
    required: true
  debug:
    description: "Whether the output debug messages to the console."
    type: boolean
    required: false
    default: false
outputs:
  updates-available:
    description: "Indicates whether dependency updates were found (true/false)."
  pr-url:
    description: "The URL of the created or updated pull request."
runs:
  using: node20
  main: index.js
