const core = require('@actions/core');
const exec = require('@actions/exec');
const github = require('@actions/github');

async function run() {
  /*
  1. Parse inputs:
    - base-branch from which to check for updates
    - target branch to use to create a PR with updates
    - Github token for authentication purposes (to create PRs)
    - Working directory where package.json and package-lock.json/yarn.lock are located
  2. Execute 'npm update' within the working directory
    For real action we would use 'npx npm-check-updates' to update package.json first, then 'npm install' to update package-lock.json
  3. If package*.json file was not modified, exit. Else
    - Add commit to the target branch
    - Create a PR to the base branch from the target branch using octokit API
  */
  core.info('I am a custom JS action');

  // 1 Parse inputs
  const baseBranch = core.getInput('base-branch') || 'main';
  const targetBranch = core.getInput('target-branch', { required: true }) || 'dependency-updates';
  const ghToken = core.getInput('gh-token', { required: true });
  const workingDirectory = core.getInput('working-directory', { required: true }) || '.';
  const DEBUG = core.getBooleanInput('debug') || false;

  const commonExecOpts = { cwd: workingDirectory };

  core.setSecret(ghToken);

  // validate inputs

  // Branch names should contain only letters, digits, underscores, hyphens, dots, and forward slashes
  const branchNamePattern = /^[a-zA-Z0-9_.-]+$/;

  if (!branchNamePattern.test(baseBranch)) {
    core.setFailed(`Invalid base branch name: ${baseBranch}`);
    return;
  }

  if (!branchNamePattern.test(targetBranch)) {
    core.setFailed(`Invalid target branch name: ${targetBranch}`);
    return;
  }

  // Directory paths should contain only letters, digits, underscores, hyphens, and forward slashes
  const directoryPathPattern = /^[a-zA-Z0-9_./-]+$/;

  if (!directoryPathPattern.test(workingDirectory)) {
    core.setFailed(`Invalid working directory path: ${workingDirectory}`);
    return;
  }

  core.info(`[js-dependency-update] Base branch: ${baseBranch}`);
  core.info(`[js-dependency-update] Target branch: ${targetBranch}`);
  core.info(`[js-dependency-update] Working directory: ${workingDirectory}`);
  core.info(`[js-dependency-update] Debug mode: ${DEBUG}`);

  // 2. Execute 'npm update' within the working directory

  await exec.exec('npm', ['update'], { ...commonExecOpts });

  // 3. Check if there are changes
  let gitStatusOutput = exec.getExecOutput('git', ['status', '-s', 'package*.json'], { ...commonExecOpts });

  if (!await gitStatusOutput) {
    core.info('[js-dependency-update] No dependency updates found. Exiting.');
    return;
  }

  // There are changes, proceed with the next steps
  core.info('[js-dependency-update] Dependency updates found. Proceeding to create a pull request...');

  await exec.exec('git', ['config', '--global', 'user.name', 'gh-automation-bot']);
  await exec.exec('git', ['config', '--global', 'user.email', 'gh-automation-bot@example.com']);

  // 4. Create and switch to the target branch, commit and pushchanges
  core.info(`[js-dependency-update] Creating and switching to branch: ${targetBranch}`);
  await exec.exec('git', ['checkout', '-B', targetBranch], { ...commonExecOpts });
  core.info('[js-dependency-update] Committing and pushing changes...');
  await exec.exec('git', ['add', 'package*.json'], { ...commonExecOpts });
  core.info('[js-dependency-update] Changes added to git staging area.');
  await exec.exec('git', ['commit', '-m', 'chore (auto): update dependencies']);
  core.info('[js-dependency-update] Changes committed.');
  await exec.exec('git', ['push', '-u', 'origin', targetBranch, '--force'], { ...commonExecOpts });
  core.info('[js-dependency-update] Changes pushed to remote repository.');

  // 5. Create a PR to the base branch from the target branch using octokit API
  core.info('[js-dependency-update] Creating a pull request...');
  const octokit = github.getOctokit(ghToken);

  try {
    await octokit.rest.pulls.create({
      owner: github.context.repo.owner,
      repo: github.context.repo.repo,
      title: 'chore (auto): update NPM dependencies',
      body: 'This is an automated pull request generated by the js-dependency-update action to update NPM dependencies.',
      head: targetBranch,
      base: baseBranch,
    });
  } catch (e) {
    core.setFailed(`[js-dependency-update] Failed to create pull request: ${e.message}`);
    return;
  }

}

run();
