name: 02 - Workflow Events

on:
  pull_request:
  schedule:
    - cron: '45 11 * * 0'  # Every Sunday at 11:45 AM
  workflow_dispatch:

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Show the trigger
        run: echo "Triggered by a ${GITHUB_EVENT_NAME} event."
