name: 04 - Using Actions

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: sample-apps/react-app
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      # - name: Printing Folders
      #   run: find . -maxdepth 3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '20.19.5'
      - name: Install Dependencies
        # working-directory: sample-apps/react-app
        run: |
          npm ci
      - name: Run Unit Tests
        # working-directory: sample-apps/react-app
        run: npm run test
