name: 05 - 2 - Event Filters and Activity Types

on:
  workflow_dispatch:
  # pull_request:
  #   types: [closed]
  #   branches:
  #     - main

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Print info
        run: |
          echo "Running whenever a PR is closed AND base branch is main."