name: 06 - Contexts

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  echo-data:
    runs-on: ubuntu-latest
    env:
      MY_ENV_VAR: "Hello, World!"
    steps:
      - name: Display Information
        run: |
          echo "Event name: ${{ github.event_name }}"
          echo "Ref: ${{ github.ref }}"
          echo "SHA: ${{ github.sha }}"
          echo "Actor: ${{ github.actor }}"
          echo "Repository: ${{ github.repository }}"
          echo "Workflow: ${{ github.workflow }}"
          echo "Job: ${{ github.job }}"
          echo "Run ID: ${{ github.run_id }}"
          echo "Run Number: ${{ github.run_number }}"
          echo "Event Path: ${{ github.event_path }}"
      - name: Retrieve Variable
        run: |
          echo "My custom environment variable: ${{ env.MY_ENV_VAR }}"
          echo "My custom repository variable: ${{ vars.MY_REPO_VAR }}"
