name: 06 - Contexts

on:
  workflow_dispatch:
    inputs:
      debug:
        description: 'Enable debug mode'
        type: boolean
        required: false
        default: false
  # push:
  #   branches:
  #     - main

run-name: "06 - Contexts | DEBUG - ${{ inputs.debug }}"

env:
  MY_WORKFLOW_VAR: "workflow"
  MY_OVERWRITTEN_VAR: "workflow"

jobs:
  echo-data:
    runs-on: ubuntu-latest
    env:
      MY_ENV_VAR: "Hello, World!"
      MY_JOB_VAR: "job"
      MY_OVERWRITTEN_VAR: "job"
    steps:
      - name: Display Information
        run: |
          echo "Event name: ${{ github.event_name }}"
          echo "Ref: ${{ github.ref }}"
          echo "SHA: ${{ github.sha }}"
          echo "Actor: ${{ github.actor }}"
          echo "Repository: ${{ github.repository }}"
          echo "Workflow: ${{ github.workflow }}"
          echo "Job: ${{ github.job }}"
          echo "Run ID: ${{ github.run_id }}"
          echo "Run Number: ${{ github.run_number }}"
          echo "Event Path: ${{ github.event_path }}"
      - name: Retrieve Variable
        run: |
          echo "My custom environment variable: ${{ env.MY_ENV_VAR }}"
          echo "My custom repository variable: ${{ vars.MY_REPO_VAR }}"
      - name: Print Env Variables
        env:
          MY_OVERWRITTEN_VAR: "step"
        run: |
          echo "MY_WORKFLOW_VAR: ${{ env.MY_WORKFLOW_VAR }}"
          echo "MY_JOB_VAR: ${{ env.MY_JOB_VAR }}"
          echo "MY_OVERWRITTEN_VAR: ${{ env.MY_OVERWRITTEN_VAR }}"
      - name: Print Env Variables 2
        run: |
          echo "MY_WORKFLOW_VAR: ${{ env.MY_WORKFLOW_VAR }}"
          echo "MY_JOB_VAR: ${{ env.MY_JOB_VAR }}"
          echo "MY_OVERWRITTEN_VAR: ${{ env.MY_OVERWRITTEN_VAR }}"
