name: 07 - Using Expressions

on:
  workflow_dispatch:
    inputs:
      debug:
        description: 'Enable debug mode'
        type: boolean
        required: false
        default: false
  # push:

run-name: "07 - Using Expressions | DEBUG - ${{ inputs.debug == true && 'ON' || 'OFF' }}"

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: "[debug] Print start-up data"
        if: ${{ inputs.debug == true }}
        run: |
          echo "Triggered by: ${{ github.event_name }}"
          echo "Branch: ${{ github.ref }}"
          echo "Commit SHA: ${{ github.sha }}"
          echo "Runner OS: ${{ runner.os }}"
      - name: "[debug] Print when triggered from main"
        if: ${{ inputs.debug == true && github.ref == 'refs/heads/main' }}
        run: |
          echo "This workflow was triggered from the main branch."
      - name: Greeting
        run: |
          echo ${{ format('Hello, {0}!', github.actor) }}
