name: 08 - Using Variables
on:
  workflow_dispatch:
  # push:
env:
  WORKFLOW_VAR: "I am a workflow env var"
  OVERWRITTEN: "I will be overwritten"
jobs:
  echo:
    runs-on: ubuntu-latest
    env:
      JOB_VAR: "I am a job env var"
      OVERWRITTEN: "I have been overwritten at job level"
    steps:
      - name: Print Env Variables
        env:
          STEP_VAR: "I am a step env var"
          step_var2: "I am another step env var"
        run: |
          echo "STEP_VAR: ${{ env.STEP_VAR }}"
          echo "step_var2: ${{ env.step_var2 }}"
          echo "JOB_VAR: ${{ env.JOB_VAR }}"
          echo "WORKFLOW_VAR: ${{ env.WORKFLOW_VAR }}"
          echo "OVERWRITTEN: ${{ env.OVERWRITTEN }}"
      - name: Overwrite Job Variable
        env:
          OVERWRITTEN: "'I have been overwritten at the step level"
        run: |
          echo "OVERWRITTEN: ${{ env.OVERWRITTEN }}"
