name: 14 - Working with Artifacts
on:
  workflow_dispatch:
jobs:
  test-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: sample-apps/react-app
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 20.x
      - name: Download cached dependencies
        id: build-cache
        uses: actions/cache@v4
        with:
          path: sample-apps/react-app/node_modules
          key: deps-node-modules-${{ hashFiles('sample-apps/react-app/package-lock.json') }}
      - name: Install dependencies
        if: ${{ steps.build-cache.outputs.cache-hit != 'true' }}
        run: npm ci
      - name: Build code
        run: npm run build
      - name: Upload built files
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: sample-apps/react-app/build
  deploy:
    runs-on: ubuntu-latest
    needs: test-build
    steps:
      - name: Download build files
        uses: actions/download-artifact@v4
        with:
          name: app
          path: build
      - name: Show folder structure
        run: ls -R
