name: 15 - Working with Matrices
on:
  workflow_dispatch:
jobs:
  backwards-compatibility:
    name: backwards-compatibility on ${{ matrix.operating-system }}/node v${{ matrix.node-version }}
    runs-on: ubuntu-lates
    strategy:
      matrix:
        node-version: ['18.x', '20.x', '21.x']
        operating-system: [ubuntu-latest, windows-latest]
    steps:
      - name: Setup node
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
      - name: Perform some tests
        run: echo "Running tests on OS ${{ matrix.operating-system }} and NodeJS ${{ matrix.node-version }}"
